"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jonas Brusman"
email = "jonas@brusman.se"

[ui]
pager = "delta"
default-command = "status"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
ll = [
    "log",
    "-r",
    "trunk()..@ | @..trunk() | trunk() | @:: | fork_point(trunk() | @)",
    "-T",
    "builtin_log_oneline",
]
rmain = ["rebase", "-r", "@", "-d", "main@origin"]

[git]
write-change-id-header = true
