"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Jonas Brusman"
email = "jonas@brusman.se"

[ui]
pager = ":builtin"
default-command = "log"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
